Make notification
dvabidonamoloka/standupstoreparser pull request #2
Opened 2020-03-05 22:44 UTC by OdintsovTim

2020-03-05 22:58 UTC, gaisin requested changes

2020-03-05 22:58 UTC, gaisin commented on .gitignore
> +__pycache__
не хватает пустой строчки в конце файла

2020-03-05 22:58 UTC, gaisin commented on .gitignore
> +__pycache__
сделай один коммит для гитигнора, пожалуйста, и укажи, что добавил, примерно так:
`gitignore: add private files, vscode settings and pycache files`

2020-03-05 22:58 UTC, gaisin commented on susp/notifications.py
> +def post_to_channel(message):
можно сразу залогировать, что сообщение отправлено

2020-03-05 22:58 UTC, gaisin commented on requirements.txt
> +beautifulsoup4==4.8.2
коммит мессадж предлагаю написать примерно так:
`requirements: add libs for telegram notifications`

2020-03-06 22:05 UTC, gaisin commented on .gitignore
> +.vscode
[Почитай](https://habr.com/ru/post/202696/) про global gitignore и добавь эту строчку в свой глобальный гитигнор

2020-03-06 22:06 UTC, gaisin commented on .gitignore
> +.vscode
pycache туда же

2020-03-11 22:31 UTC, OdintsovTim commented on .gitignore
> +.vscode
Судя по комментам в ссылке - спорный момент, так как при работе в команде нужно будет при каждом проекте настраивать централизованно для всех глобальный гитигнор. Уверен, что в данном случае так будет лучше?

2020-03-11 22:40 UTC, gaisin commented on .gitignore
> +.vscode
Не совсем, каждый член команды на своем компе настраивает для себя глобальный гитигнор. Например, ты работает в vscode, и добавляешь в свой гитигнор `.vscode`, чтобы во всех проектах на твоем компе эта папка не учитывалась гитом. Другой человек может работать в pycharm, тогда он у себя добавит строчку `.idea`

2020-03-11 22:42 UTC, gaisin commented on .gitignore
> +.vscode
В целом неплохо научиться пользоваться этим: ты сможешь добавлять в репозиторий личные файлы — какие-нибудь тестовые скрипты или еще что-то, при этом они не будут мешаться, когда ты будешь коммитить изменения в основные файлы репозитория.

2020-03-12 08:23 UTC, gaisin approved these changes

2020-03-12 09:56 UTC, merged