Make event notifications
dvabidonamoloka/standupstoreparser pull request #8
Opened 2020-03-15 00:59 UTC by OdintsovTim

2020-03-15 09:35 UTC, gaisin requested changes

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +    LOG.info('Templates made')
Не уверен, что это требует логирования, разве что в уровне debug
и не совсем корректно, что template made, т.к. template — это шаблон, а ты уже сформировал конкретное сообщение, может надо написать что-то вроде _"The text of the message is generated."_

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +def make_message_template(event):
Все-таки мы здесь не делаем шаблон сообщения, а формируем письмо, поэтому может назвать типа `generate_event_message`?
Тоже самое про докстринг

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +    LOG.info('check data availability')
Лучше убрать логику проверки доступности мероприятия из функций уведомления, это не должно быть ее заботой.
Функция уведомления должна просто сформировать сообщение и уведомить исходя из входных данных.

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +    message = make_message_template()
эта функция же аргумент принимает, а ты ей ничего не передал)

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +        post_to_channel(message)
может сделать проще:
```python
if message:
    post_to_channel(message)
```

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +    '''Creates message and post it to the channel'''
posts
и точка в конце предложения

2020-03-15 09:35 UTC, gaisin commented on susp/notifications.py
> +        LOG.error('Poster url missing. Unable to send message')
ты же не сообщение отправляешь, поэтому _unable to generate the message_
И предложение по формату: "Unable to generate a message: poster url is missing"

2020-03-19 09:42 UTC, gaisin requested changes

2020-03-19 09:42 UTC, gaisin commented on susp/notifications.py
> +        template = f'Дата:[ ]({poster_url}){date}\nЦена: {price}\nОсталость мест: {seats}\n[Купить билеты]({url})'
опять же лучше назвать это `message`, т.к. в переменную ты получаешь не шаблон, а готовое сообщение

2020-03-19 09:42 UTC, gaisin commented on susp/notifications.py
> +        poster_url = event.poster_url
может возникнуть случай, когда есть `event.url`, но нет `event.poster_url`
не нужно ли значение по умолчанию в таком случае?

2020-03-19 09:42 UTC, gaisin commented on susp/notifications.py
> +        poster_url = event.poster_url
еще сейчас потестил — если у `event` не будет какого-то атрибута, то будет ошибка
```python
>>> asdf = event.asdf or "asdf"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Event' object has no attribute 'asdf'
```
поэтому здесь еще надо будет подумать, как лучше сделать

2020-03-19 09:42 UTC, gaisin commented on susp/notifications.py
> +    LOG.debug('Сhecking data availability in Event instance and generating message')
мне кажется `Generating event message` достаточно)

2020-03-19 09:53 UTC, gaisin commented on susp/notifications.py
> +    Create message to notificate about new event or
`creates`, потому что ты уже так начал в `make_notification` и `post_to_channel`
а вообще можно и в императиве писать, но желательно придерживаться одного стиля в проекте

2020-03-19 15:54 UTC, OdintsovTim commented on susp/notifications.py
> +        poster_url = event.poster_url
Странно, но не нужно. Он не считывает в этом случае пробел в квадратных скобках

2020-03-19 20:31 UTC, gaisin approved these changes
Молодец!
засквош фиксапы, плз)

2020-03-19 20:44 UTC, merged